students=('Nandha' 'Akshay' 'pooja' 'Shilpa')

echo "Array Is : ${students[@]}"

echo "******************CREATE************************"
echo "Before Create"
echo "Array Is : ${students[@]}"
students[4]="Swathy"
echo "After Create"
echo "Array Is : ${students[@]}"
echo "************************************************"
echo "******************READ**************************"
echo "Read all In Our Bucket"
echo "Array Is : ${students[@]}"
echo "Read Specific with Index Number"
echo "Array Is : ${students[2]}"
echo "************************************************"

echo "******************UPDATE************************"
echo "Before Update"
echo "Array Is : ${students[@]}"
students[1]="Prachi"
echo "After Update"
echo "Array Is : ${students[@]}"
echo "************************************************"
echo "******************DELETE************************"
echo "Before Delete"
echo "Array Is : ${students[@]}"
unset 'students[3]'
echo "After Delete"
echo "Array Is : ${students[@]}"
echo "************************************************"

echo "********Display Only Index Numbers**************"
echo "${!students[@]}"
echo "************************************************"
echo "********Length Of an Array**********************"
echo "${#students[@]}"
echo "************************************************"
