declare -A movies
movies[tamil]="master"
movies[malayalam]="kurup"
movies[hindi]="pushpa"
movies[telugu]="bahubali"

echo "******************CREATE************************"
echo "Before Create"
echo "Dictionary Is : ${movies[@]}"
movies[english]="spiderman"
echo "After Create"
echo "Dictionary Is : ${movies[@]}"
echo "************************************************"
echo "******************READ**************************"
echo "Read all In Our Dictionary"
echo "Dictionary Is : ${movies[@]}"
echo "Read Specific with Key"
echo "Dictionary Is : ${movies[telugu]}"
echo "************************************************"
echo "******************UPDATE************************"
echo "Before Update"
echo "Dictionary Is : ${movies[@]}"
movies[telugu]="arjunreddy"
echo "After Update"
echo "Dictionary Is : ${movies[@]}"
echo "************************************************"
echo "******************DELETE************************"
echo "Before Delete"
echo "Dictionary Is : ${movies[@]}"
unset 'movies[tamil]'
echo "After Delete"
echo "Dictionary Is : ${movies[@]}"
echo "************************************************"
echo "********Display Only Keys**************"
echo "${!movies[@]}"
echo "************************************************"
echo "********Length Of an Dictionary**********************"
echo "${#movies[@]}"
echo "************************************************"